/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ufps.GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultEditorKit;
/**
 *
 * @author Rosemberg
 */
public class FormCopyPaste extends javax.swing.JFrame {
private JButton boton;
private boolean val=true;
private FormOperaciones myForm;

    /**
     * Creates new form FormCopyPaste
     */
    public FormCopyPaste(FormOperaciones form, String link) {
        
        initComponents();
        this.myForm=form;
        setLocationRelativeTo(null);
        this.boton= new JButton(new DefaultEditorKit.CopyAction());
        boton.setText("Copiar");
        boton.setBounds(100, 90, 100, 30);
        boton.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
              accion();
            }
        });
        this.add(boton);
        this.txtVal.setText(link);
        this.txtVal.setSelectionStart(0);
        this.txtVal.setSelectionEnd(txtVal.getText().length());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtVal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Copiar Link");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        txtVal.setEditable(false);
        txtVal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtVal, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(txtVal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtValActionPerformed

    
    public void accion(){
        
        if(val){
           
        this.val=false;
        JOptionPane.showMessageDialog(null, "El link ha sido guardado en su portapapeles","Copiado",JOptionPane.OK_OPTION);
        this.txtVal.setEnabled(false);
        this.boton.setText("Salir");
        }
        else
            this.dispose();
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField txtVal;
    // End of variables declaration//GEN-END:variables
}
